services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: gearplay
      POSTGRES_PASSWORD: motdepasse_secret
      POSTGRES_DB: gearplay
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: